//! Native DOM storage components, independent of JavaScript realm management.
mod attribute_index;
mod attribute_operations;
mod attribute_view;
mod attributes;
mod boundary_points;
mod character_data;
mod constants;
mod data;
mod error;
mod namespaces;
mod node_comparison;
mod node_metadata;
mod node_text;
mod normalization;
mod queries;
mod range_boundaries;
mod range_queries;
mod range_text;
mod selector_element;
mod selector_syntax;
mod serialization;
mod store;
pub mod tree;
mod unicode_case;
