/** Exercises named/default ESM exports, native contracts and the installed Vitest VM adapter. */
import assert from 'node:assert/strict';
import runtime, { JSDOM, CookieJar, getNativeTreeStatistics } from '@rustdom/rustdom';
import { NativeTree, QueryMode, DocumentTypeField } from '@rustdom/rustdom/native';
import environment from '@rustdom/rustdom/vitest';

assert.equal(runtime.JSDOM, JSDOM);
const dom = new JSDOM('<!doctype html><p>Hello</p>', { cookieJar: new CookieJar() });
dom.window.document.body.insertAdjacentHTML('beforeend', '<span>Installed</span>');
assert.equal(dom.window.document.querySelector('span')?.textContent, 'Installed');
assert.ok(getNativeTreeStatistics().dataNodes > 0);
const nativeTree = new NativeTree();
const doctype = nativeTree.allocate();
nativeTree.initializeDocumentType(doctype, 'html', 'public', 'system');
assert.equal(nativeTree.documentTypeField(doctype, DocumentTypeField.SystemId), 'system');
nativeTree.release(doctype);
assert.equal(nativeTree.statistics().liveNodes, 0);
assert.equal(QueryMode.First, 1);
dom.window.close();
assert.ok(environment.setupVM);
const session = await environment.setupVM({ jsdom: { html: '<p>VM package</p>' } });
const context = session.getVmContext();
assert.equal(context.document.querySelector('p').textContent, 'VM package');
assert.equal(context.document.querySelector('p').firstChild.nodeValue, 'VM package');
const paragraph = context.document.querySelector('p');
paragraph.append(context.document.createTextNode(' appended'));
paragraph.normalize();
assert.equal(paragraph.childNodes.length, 1);
assert.equal(paragraph.textContent, 'VM package appended');
assert.ok(context.document.body.contains(context.document.querySelector('p')));
assert.ok(context.document.body.isEqualNode(context.document.body.cloneNode(true)));
context.document.body.setAttributeNS('http://www.w3.org/2000/xmlns/', 'xmlns:p', 'urn:vm');
assert.equal(context.document.querySelector('p').lookupNamespaceURI('p'), 'urn:vm');
await session.teardown();
